services:
  flask-app:
    build: .
    ports:
      - "5001:5001"  
    depends_on:
      - redis  

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data  
volumes:
  redis-data:


